package gator.lib.i18;/* Automatically generated by GNU msgfmt.  Do not modify!  */
public class Messages_en extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[64];
    t[0] = "";
    t[1] = "Project-Id-Version: 0.1\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2012-08-16 12:08+local\nLast-Translator: Sergio Basurto <sbasurto@soft-gator.com>\nLanguage-Team: ENGLISH <services@soft-gator.com>\nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n";
    t[6] = "Sin Observaciones";
    t[7] = "No Remarks";
    t[12] = "Search and select the account and warehouse you want to use";
    t[13] = "Search and select the account and warehouse you want to use";
    t[16] = "Account, warehouse or identifier";
    t[17] = "Account, warehouse or identifier";
    t[24] = "CONFIRMADO";
    t[25] = "CONFIRMED";
    t[28] = "INGRESADO";
    t[29] = "CAPTURED";
    t[36] = "WMS System";
    t[37] = "Gator System";
    t[38] = "Next";
    t[39] = "Next";
    t[44] = "results";
    t[45] = "results";
    t[46] = "Previous";
    t[47] = "Previous";
    t[52] = "Pagination";
    t[53] = "Pagination";
    t[56] = "Ent por Defecto";
    t[57] = "Default Inbound";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 32) << 1;
    java.lang.Object found = table[idx];
    if (found != null && msgid.equals(found))
      return table[idx + 1];
    return null;
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 64 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 64);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 64 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
