package gator.lib.i18;/* Automatically generated by GNU msgfmt.  Do not modify!  */
public class Messages_en extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[178];
    t[0] = "";
    t[1] = "Project-Id-Version: 0.1\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2012-08-16 12:08+local\nLast-Translator: Sergio Basurto <sbasurto@soft-gator.com>\nLanguage-Team: ENGLISH <services@soft-gator.com>\nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n";
    t[2] = "Counted Quantity";
    t[3] = "Counted Quantity";
    t[4] = "Transfer Quantity";
    t[5] = "Transfer Quantity";
    t[12] = "Extra 0";
    t[13] = "Extra 0";
    t[16] = "CONFIRMADO";
    t[17] = "CONFIRMED";
    t[18] = "Extra 3";
    t[19] = "Extra 3";
    t[20] = "Extra 4";
    t[21] = "Extra 4";
    t[22] = "Extra 5";
    t[23] = "Extra 5";
    t[24] = "Extra 6";
    t[25] = "Extra 6";
    t[26] = "Extra 7";
    t[27] = "Extra 7";
    t[32] = "Approve this access from Gator Mobile.";
    t[33] = "Approve this access from Gator Mobile.";
    t[34] = "The product must exists in location";
    t[35] = "The product must exists in location";
    t[40] = "Salida Det Id";
    t[41] = "Salida Det Id";
    t[42] = "Select RFId Packing";
    t[43] = "Select RFId Packing";
    t[46] = "Pagination";
    t[47] = "Pagination";
    t[50] = "Start a new session if this rejection was a mistake.";
    t[51] = "Start a new session if this rejection was a mistake.";
    t[52] = "SKU";
    t[53] = "SKU";
    t[54] = "Entrada Det Id";
    t[55] = "Entrada Det Id";
    t[60] = "Ent por Defecto";
    t[61] = "Default Inbound";
    t[70] = "Skip 2";
    t[71] = "Skip 2";
    t[72] = "SID";
    t[73] = "SID";
    t[74] = "Location Information";
    t[75] = "Location Information";
    t[80] = "Use another verification method";
    t[81] = "Use another verification method";
    t[84] = "Previous";
    t[85] = "Previous";
    t[86] = "Extra 2";
    t[87] = "Extra 2";
    t[96] = "Entra 1";
    t[97] = "Entra 1";
    t[102] = "The access request was rejected from Gator Mobile.";
    t[103] = "The access request was rejected from Gator Mobile.";
    t[110] = "Search and select the account and warehouse you want to use";
    t[111] = "Search and select the account and warehouse you want to use";
    t[112] = "Select Packing";
    t[113] = "Select Packing";
    t[114] = "Next";
    t[115] = "Next";
    t[120] = "SID Information";
    t[121] = "SID Information";
    t[124] = "Packing Information";
    t[125] = "Packing Information";
    t[128] = "Check authorization";
    t[129] = "Check authorization";
    t[142] = "Sin Observaciones";
    t[143] = "No Remarks";
    t[144] = "Dummy 1";
    t[145] = "Dummy 1";
    t[146] = "Staying Ok";
    t[147] = "Staying Ok";
    t[150] = "The SID must exists in location";
    t[151] = "The SID must exists in location";
    t[154] = "results";
    t[155] = "results";
    t[156] = "Add Items";
    t[157] = "Add Items";
    t[160] = "Serial Numbers";
    t[161] = "Serial Numbers";
    t[164] = "INGRESADO";
    t[165] = "CAPTURED";
    t[166] = "Account, warehouse or identifier";
    t[167] = "Account, warehouse or identifier";
    t[168] = "Movements";
    t[169] = "Movements";
    t[170] = "Inbound OP";
    t[171] = "Inbound OP";
    t[174] = "WMS System";
    t[175] = "Gator System";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 89) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 87) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 178)
        idx -= 178;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 178 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 178);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 178 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
