package gator.lib.i18;/* Automatically generated by GNU msgfmt.  Do not modify!  */
public class Messages_en extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[442];
    t[0] = "";
    t[1] = "Project-Id-Version: 0.1\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2012-08-16 12:08+local\nLast-Translator: Sergio Basurto <sbasurto@soft-gator.com>\nLanguage-Team: ENGLISH <services@soft-gator.com>\nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n";
    t[8] = "Next";
    t[9] = "Next";
    t[12] = "Waste (kg)";
    t[13] = "Waste (kg)";
    t[20] = "Receive roll";
    t[21] = "Receive roll";
    t[24] = "WMS System";
    t[25] = "Gator System";
    t[26] = "Salida Det Id";
    t[27] = "Salida Det Id";
    t[30] = "Initial weight (kg)";
    t[31] = "Initial weight (kg)";
    t[36] = "Reprint label";
    t[37] = "Reprint label";
    t[40] = "Fabric Roll Control";
    t[41] = "Fabric Roll Control";
    t[42] = "Cancel cut order";
    t[43] = "Cancel cut order";
    t[48] = "Provider";
    t[49] = "Provider";
    t[52] = "Approve this access from Gator Mobile.";
    t[53] = "Approve this access from Gator Mobile.";
    t[56] = "Close cut and print";
    t[57] = "Close cut and print";
    t[58] = "Add Items";
    t[59] = "Add Items";
    t[62] = "Destination location";
    t[63] = "Destination location";
    t[66] = "Cut status";
    t[67] = "Cut status";
    t[68] = "Scrap 3 weight (kg)";
    t[69] = "Scrap 3 weight (kg)";
    t[74] = "Serial Numbers";
    t[75] = "Serial Numbers";
    t[76] = "Entrada Det Id";
    t[77] = "Entrada Det Id";
    t[78] = "Fabric Rolls";
    t[79] = "Fabric Rolls";
    t[80] = "The product must exists in location";
    t[81] = "The product must exists in location";
    t[86] = "Use another verification method";
    t[87] = "Use another verification method";
    t[94] = "Scan fabric";
    t[95] = "Scan fabric";
    t[108] = "Start a new session if this rejection was a mistake.";
    t[109] = "Start a new session if this rejection was a mistake.";
    t[110] = "Scrap 1 name";
    t[111] = "Scrap 1 name";
    t[114] = "Scrap 4 name";
    t[115] = "Scrap 4 name";
    t[120] = "Ent por Defecto";
    t[121] = "Default Inbound";
    t[124] = "Save";
    t[125] = "Save";
    t[132] = "Extra 0";
    t[133] = "Extra 0";
    t[136] = "Extra 2";
    t[137] = "Extra 2";
    t[138] = "Extra 3";
    t[139] = "Extra 3";
    t[140] = "Extra 4";
    t[141] = "Extra 4";
    t[142] = "Extra 5";
    t[143] = "Extra 5";
    t[144] = "Extra 6";
    t[145] = "Extra 6";
    t[146] = "Extra 7";
    t[147] = "Extra 7";
    t[152] = "Status";
    t[153] = "Status";
    t[158] = "Weight sent to production (kg)";
    t[159] = "Weight sent to production (kg)";
    t[168] = "Tolerance (kg)";
    t[169] = "Tolerance (kg)";
    t[170] = "Send to cutting";
    t[171] = "Send to cutting";
    t[172] = "SID Information";
    t[173] = "SID Information";
    t[182] = "Select Packing";
    t[183] = "Select Packing";
    t[184] = "Inbound OP";
    t[185] = "Inbound OP";
    t[186] = "Scale";
    t[187] = "Scale";
    t[194] = "Skip 2";
    t[195] = "Skip 2";
    t[198] = "Purchase order / Inbound";
    t[199] = "Purchase order / Inbound";
    t[204] = "Scan or enter order";
    t[205] = "Scan or enter order";
    t[206] = "SID";
    t[207] = "SID";
    t[208] = "The access request was rejected from Gator Mobile.";
    t[209] = "The access request was rejected from Gator Mobile.";
    t[212] = "Fabric Roll";
    t[213] = "Fabric Roll";
    t[214] = "Scrap 6 weight (kg)";
    t[215] = "Scrap 6 weight (kg)";
    t[216] = "Scrap 5 weight (kg)";
    t[217] = "Scrap 5 weight (kg)";
    t[218] = "Previous";
    t[219] = "Previous";
    t[224] = "Pagination";
    t[225] = "Pagination";
    t[226] = "Packing Information";
    t[227] = "Packing Information";
    t[228] = "Remaining roll (kg)";
    t[229] = "Remaining roll (kg)";
    t[236] = "Search and select the account and warehouse you want to use";
    t[237] = "Search and select the account and warehouse you want to use";
    t[240] = "Roll Id";
    t[241] = "Roll Id";
    t[242] = "Difference (kg)";
    t[243] = "Difference (kg)";
    t[252] = "Scrap 2 weight (kg)";
    t[253] = "Scrap 2 weight (kg)";
    t[254] = "Select RFId Packing";
    t[255] = "Select RFId Packing";
    t[258] = "Fabric";
    t[259] = "Fabric";
    t[260] = "Scrap 3 name";
    t[261] = "Scrap 3 name";
    t[262] = "CONFIRMADO";
    t[263] = "CONFIRMED";
    t[264] = "Check authorization";
    t[265] = "Check authorization";
    t[266] = "Choose";
    t[267] = "Choose";
    t[268] = "Entra 1";
    t[269] = "Entra 1";
    t[274] = "Receive and print";
    t[275] = "Receive and print";
    t[278] = "The SID must exists in location";
    t[279] = "The SID must exists in location";
    t[280] = "Print label";
    t[281] = "Print label";
    t[282] = "Cut outbound weight (kg)";
    t[283] = "Cut outbound weight (kg)";
    t[286] = "Location Information";
    t[287] = "Location Information";
    t[296] = "Put away";
    t[297] = "Put away";
    t[298] = "Dummy 1";
    t[299] = "Dummy 1";
    t[302] = "Create cut order";
    t[303] = "Create cut order";
    t[308] = "Fabric SKU";
    t[309] = "Fabric SKU";
    t[318] = "Transfer Quantity";
    t[319] = "Transfer Quantity";
    t[322] = "Scan location";
    t[323] = "Scan location";
    t[326] = "Scrap 4 weight (kg)";
    t[327] = "Scrap 4 weight (kg)";
    t[328] = "Counted Quantity";
    t[329] = "Counted Quantity";
    t[330] = "New fabric";
    t[331] = "New fabric";
    t[334] = "Cut order";
    t[335] = "Cut order";
    t[342] = "Scrap 6 name";
    t[343] = "Scrap 6 name";
    t[344] = "Current location";
    t[345] = "Current location";
    t[348] = "Sin Observaciones";
    t[349] = "No Remarks";
    t[350] = "Fabric Cut Order";
    t[351] = "Fabric Cut Order";
    t[360] = "Account, warehouse or identifier";
    t[361] = "Account, warehouse or identifier";
    t[362] = "Show";
    t[363] = "Show";
    t[364] = "SKU";
    t[365] = "SKU";
    t[366] = "INGRESADO";
    t[367] = "CAPTURED";
    t[374] = "Auto filled";
    t[375] = "Auto filled";
    t[376] = "results";
    t[377] = "results";
    t[378] = "Fabric Cut Orders";
    t[379] = "Fabric Cut Orders";
    t[384] = "Movements";
    t[385] = "Movements";
    t[386] = "Save and print";
    t[387] = "Save and print";
    t[398] = "Current weight (kg)";
    t[399] = "Current weight (kg)";
    t[406] = "Scrap 2 name";
    t[407] = "Scrap 2 name";
    t[410] = "Scrap 5 name";
    t[411] = "Scrap 5 name";
    t[414] = "Staying Ok";
    t[415] = "Staying Ok";
    t[436] = "Scrap 1 weight (kg)";
    t[437] = "Scrap 1 weight (kg)";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 221) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 219) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 442)
        idx -= 442;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 442 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 442);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 442 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
